name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: |
          msbuild AstroGolf.sln /t:build /p:Configuration=Release /p:Platform=x64
      
      - run: |
          ls
      
      - name: Copy assets to Release directory
        run: |
          Copy-Item -Path "AstroGolf/assets" -Destination "x64/Release/" -Recurse -Force
      
      - name: Create release archive
        run: |
          Compress-Archive -Path "AstroGolf/x64/Release/*" -DestinationPath "AstroGolf-build.$BUILD_NUMBER.zip"
      
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: "AstroGolf-build.$BUILD_NUMBER"
          path: "AstroGolf-build.$BUILD_NUMBER.zip"
